---
- hosts: all
  become: true
  gather_facts: false
  tasks:
          - name: Creating user
            user:
                    name: mark
                    password: "{{ 'eritrea' | password_hash('sha512') }}"
