---
- hosts: all
  tasks:
          - name: Display Items based on the criteria
            command:
                    echo "{{ item }}"
            loop: [1,2,3,4,5,6,7,8]
            when: item > 4
