---
- hosts: all
  become: true
  tasks:
          - name: creating multiple users using loop
            user:
                    name: "{{ item }}"
                    state: present
            loop:
                    - aramando
                    - carlos
                    - vero
                    - kaka
