---
- hosts: all
  tasks:
          - name: Displaying FQDN of Specific Nodes
            debug:
                    msg: "{{ ansible_facts['fqdn'] }}"
            when:
                    - ansible_facts['hostname'] == "mh1"
                    - ansible_facts['os_family']== "RedHat"
                    - ansible_facts['distribution_major_version'] == "8"
