---
- hosts: all
  become: true
  gather_facts: false
  vars_files: task_8.11_userslist.yml
  tasks:
          - name: Creating users for HR Department 
            user:
                    name: "{{ item.username }}"
                    state: present
            loop:
                    "{{ users }}"
            when: item.department=="HR"

